model:
  name: mtgnn
  hparams:
    residual_channels: 16
    dilation_channels: 16
    skip_channels: 32
    end_channels: 64
    n_blocks: 2
    n_layers: 2
    gcn_order: 2
    top_k: 8
    emb_dim: 16
    dropout: 0.1
    epochs: 30
    lr: 1.0e-3
    weight_decay: 1.0e-4
    patience: 7
    batch_size: 8
